### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by BlueRaja** [BlueRaja/Starbank#1]
I got a report about a crash:
http://textuploader.com/dkged

```
System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at StarBank.Bank_Stuffs.BankWriter.CreateKey(Key key)
   at StarBank.Bank_Stuffs.BankWriter.CreateKeys(IEnumerable`1 keys)
   at StarBank.Bank_Stuffs.BankWriter.CreateSection(Section section)
   at StarBank.Bank_Stuffs.BankWriter.CreateSections(IEnumerable`1 sections)
   at StarBank.Bank_Stuffs.BankWriter.CreateDocument(Bank bank)
   at StarBank.BankEditor.objectListView1_CellEditFinishing(Object sender, CellEditEventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnCellEditFinishing(CellEditEventArgs e)
   at BrightIdeasSoftware.ObjectListView.FinishCellEdit()
   at BrightIdeasSoftware.ObjectListView.PossibleFinishCellEditing()
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by BlueRaja** [comment]
Example map that repros: Cave of Blood

I now know the cause, but probably am not going to fix this because it'd be a lot of work and hardly anyone uses this anymore.

**Comment by kazzit** [comment]
Signing it causes exact same error.
